version: "2"
services:
    api:
        build: ./src
        ports:
            - "80:3000"
        env_file:
            - .env
        depends_on:
            - db
    db:
        image: postgres
        volumes:
            - data:/var/lib/postgresql/data
volumes:
    data: {}