# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 06:07
from __future__ import unicode_literals

from django.db import migrations

from dateutil import tz
import arrow

def datetime(day, hour, minute):
    return arrow.get(2018, 4 if (day == 1) else 3, day, hour, minute, 0, 0, tz.gettz('US/Central')).datetime

def generate_seed_data(apps, schema_editor):
    Location = apps.get_model("events", "Location")
    db_alias = schema_editor.connection.alias

    union_ballroom = Location(
        name="Texas Union: Sherley Bird Perry Ballroom",
        address="Texas Union Building Austin, Texas",
        latitude=30.2866649 longitude=-97.7433516,
        notes=""
    )
    union_quadrangle = Location(
        name="Texas Union: Quadrangle Room",
        address="Texas Union Building Austin, Texas",
        latitude=30.2866649 longitude=-97.7433516,
        notes=""
    )
    union_eastwoods = Location(
        name="Texas Union: Eastwoods Room",
        address="Texas Union Building Austin, Texas",
        latitude=30.2866649 longitude=-97.7433516,
        notes=""
    )
    nueces_mosque = Location(
        name="Nueces Mosque",
        address="1906 Nueces St, Austin, TX 78705",
        latitude=30.2831914, longitude=-97.7465274,
        notes=""
    )
    gregory_gym = Location(
        name="Gregory Gym: Arena 3.108",
        address="2101 Speedway, Austin, TX 78712",
        latitude=30.2842377, longitude=-97.7386967,
        notes=""
    )
    rec_sports = Location(
        name="Recreational Sports Center: Room 2.200",
        address="Recreational Sports Center, 2001 San Jacinto Blvd, Austin, TX 78705",
        latitude=30.2815448, longitude=-97.73465080,
        notes=""
    )
    clark_basketball = Location(
        name="Clark Basketball Courts",
        address="Basketball Support Building, 301 Jester Cir, Austin, TX 78712",
        latitude=30.2811592, longitude=-97.7377321,
        notes=""
    )
    whitaker_fields = Location(
        name="Wright-Whitaker Fields",
        address="4901 Guadalupe St, Austin, TX 78751",
        latitude=30.2812333, longitude=-97.7705628,
        notes=""
    )
    main_mall_tower = Location(
        name="Main Mall: UT Tower",
        address="110 Inner Campus Drive, Austin, TX 78705",
        latitude=30.2862222, longitude=-97.7415767,
        notes=""
    )
    utc_2.102A = Location(
        name="UTC: Room 2.102A",
        address="105 W 21st St, Austin TX, 78712",
        latitude=30.2832791, longitude=-97.739008,
        notes=""
    )
    utc_2.112A = Location(
        name="UTC: Room 2.112A",
        address="105 W 21st St, Austin TX, 78712",
        latitude=30.2832791, longitude=-97.739008,
        notes=""
    )
    utc_1.102 = Location(
        name="UTC: Room 1.102",
        address="105 W 21st St, Austin TX, 78712",
        latitude=30.2832791, longitude=-97.739008,
        notes=""
    )
    utc_1.130 = Location(
        name="UTC: Room 1.130",
        address="105 W 21st St, Austin TX, 78712",
        latitude=30.2832791, longitude=-97.739008,
        notes=""
    )

    Location.objects.using(db_alias).bulk_create([
        union_ballroom, union_quadrangle,
        union_eastwoods, nueces_mosque, rec_sports, gregory_gym,
        main_mall_tower, whitaker_fields,
        utc_2.102A, clark_basketball,
        utc_2.112A, utc_1.102, utc_1.130
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(generate_seed_data),
    ]
