# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 01:36
from __future__ import unicode_literals

from django.db import migrations

from dateutil import tz
import arrow

def datetime(day, hour, minute):
    return arrow.get(2018, 4 if (day == 1) else 3, day, hour, minute, 0, 0, tz.gettz('America/Chicago')).datetime

def get_event_data_from_csv():
    csv_file = open('./showdown_schedule_expanded.csv')
    event_data = []
    for line in csv_file:
        elements = line.split(',')
        name = elements[0]
        day = int(elements[1])
        start_hr, start_min = elements[2:4]
        end_hr, end_min = elements[4:6]
        audience = elements[6].strip()
        location_name = elements[-1].strip()

        start_time = datetime(day, int(start_hr), int(start_min))
        end_time = datetime(day, int(end_hr), int(end_min))
        event_data.append((name, start_time, end_time, audience, location_name))
    return event_data


def generate_seed_data(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    Location = apps.get_model("events", "Location")
    db_alias = schema_editor.connection.alias

    data = get_event_data_from_csv()
    events = []
    for d in data:
        name, start_time, end_time, audience, location_name = d
        print(name, location_name)
        event = Event(
            title=name,
            audience=audience,
            start_time=start_time,
            end_time=end_time,
            description="",
            location=Location.objects.get(name=location_name)
        )
        events.append(event)
    
    Event.objects.using(db_alias).bulk_create(events)




class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20170407_0107'),
    ]

    operations = [
        migrations.RunPython(generate_seed_data),
    ]
