# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 23:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20170325_1854'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Annoucement',
            new_name='Announcement',
        ),
    ]
