# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 00:00
from __future__ import unicode_literals

from django.db import migrations

def forwards_func(apps, schema_editor):
    Announcement = apps.get_model("notifications", "Announcement")
    db_alias = schema_editor.connection.alias
    Announcement.objects.using(db_alias).bulk_create([
        Announcement(
            title="Both of the Showdown apps are live!", 
            body="The Showdown Android and iOS apps are now live! We hope y'all enjoy them!",
       )
    ])

def reverse_func(apps, schema_editor):
    Announcement = apps.get_model("notifications", "Announcement")
    db_alias = schema_editor.connection.alias
    Announcement.objects.using(db_alias).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20170325_1859'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
