# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 00:00
from __future__ import unicode_literals

from django.db import migrations

def forwards_func(apps, schema_editor):
    Announcement = apps.get_model("notifications", "Announcement")
    db_alias = schema_editor.connection.alias
    Announcement.objects.using(db_alias).bulk_create([
        Announcement(
            title="Submission deadline for art at 4:30pm", 
            body="Submissions are due by 4:30pm. Late entries won't be judged",
       ),
        Announcement(
            title="Brother's Lunch available at IM fields", 
            body="Registered attendees can get lunch at the fields. Please have your band ready",
       ),
    ])

def reverse_func(apps, schema_editor):
    Announcement = apps.get_model("notifications", "Announcement")
    db_alias = schema_editor.connection.alias
    Announcement.objects.using(db_alias).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20170325_1859'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
