using System;
namespace Common.Common
{
	/// <summary>
	/// IPresenter is the base interface for all presenters in the app. The presenter is pretty much
	/// the controller in MVC. It reads from a view's public fields and reacts to events generated by
	/// the view
	/// </summary>
	public interface IPresenter
	{
		/// <summary>
		/// Sets the view the presenter is holding
		/// </summary>
		/// <param name="view">The view the presenter should use</param>
		void TakeView(IView view);

		/// <summary>
		/// Removes the view.
		/// </summary>
		void RemoveView();
	}
}
