using System.Threading.Tasks;

namespace Common.Common
{
	/// <summary>
	/// Presenter is the base class for all presenters in the app. The presenter is pretty much
	/// the controller in MVC. It reads from a view's public fields and reacts to events generated by
	/// the view
	/// </summary>
	public class Presenter<V>
	{
        protected V View { get; set; }

		/// <summary>
		/// Sets the view the presenter is holding
		/// </summary>
		/// <param name="view">The view the presenter should use</param>
		public virtual void TakeView(V view)
		{
			this.View = view;
		}

		/// <summary>
		/// Removes the view.
		/// </summary>
		public virtual void RemoveView()
		{
			this.View = default(V);
		}
	}
}
