namespace Common.Common
{
	using System;

	/// <summary>
	/// IPresenter is the base interface for all presenters in the app. The presenter is pretty much
	/// the controller in MVC. It reads from a view's public fields and reacts to events generated by
	/// the view
	/// </summary>
	public class Presenter<V> where V: IView
	{
		protected V view;

		/// <summary>
		/// Sets the view the presenter is holding
		/// </summary>
		/// <param name="view">The view the presenter should use</param>
		public virtual void TakeView(V view)
		{
			this.view = view;
		}

		/// <summary>
		/// Removes the view.
		/// </summary>
		public virtual void RemoveView()
		{
			this.view = default(V);
		}
	}
}
