# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
