# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_school_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='short_name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
