# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 05:52
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('facebook_id', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=200)),
                ('adminstrator', models.BooleanField(default=False)),
            ],
        ),
    ]
