# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 04:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=140)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('scorekeeper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.User')),
                ('teams', models.ManyToManyField(to='core.School')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ScoreCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.Game')),
                ('teams', models.ManyToManyField(through='scores.Score', to='core.School')),
            ],
            options={
                'get_latest_by': 'time',
            },
        ),
        migrations.AddField(
            model_name='score',
            name='score_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.ScoreCard'),
        ),
        migrations.AddField(
            model_name='score',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.School'),
        ),
    ]
